title: Карта развития python разработчика до уровня джун/мидл
description: Данная карта может быть рекомендована новичкам, которые хотят профессионально создавать программное обеспечение на языке Python 
remote_theme: cotes2020/jekyll-theme-chirpy