title: Карта развития python разработчика до уровня junior/middle
description: Данная карта может быть рекомендована новичкам, которые хотят профессионально создавать прогрманое обсеспечение на языке Python 