title: Карта развития python разработчика до уровня джун/миддл
description: Данная карта может быть рекомендована новичкам, которые хотят профессионально создавать прогрманое обсеспечение на языке Python 
remote_theme: cotes2020/jekyll-theme-chirpy